name: "Security advice"

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  security-advice:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "pcov"
          php-version: "8.1"
          ini-values: memory_limit=-1
          extensions: sodium, fileinfo

      - name: "Install dependencies"
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "locked"

      - name: "🚔 Run security advice"
        run: "composer security-advice"
